#!/bin/sh
if test "$1" = ""; then
  VERSION=`java -cp "$MP3AGIC_INSTALL_PATH/mp3agic-apps.jar:$MP3AGIC_INSTALL_PATH/mp3agic.jar" com.mpatric.mp3agic.app.LibVersion`
  echo
  echo mp3cat $VERSION
  echo
  echo "Lists the details of the specified mp3 file(s) in comma-delimited format"
  echo
  echo "Usage: mp3cat [filename specifier]"
  echo "Example: mp3cat myaudio/*.mp3 > myaudio.csv"
  echo
  exit 2
fi
fin=0
while ! ((fin)); do
  if test "$1" = ""; then
    fin=1
  else
    if [ -f "${1}" ]; then
      java -cp "$MP3AGIC_INSTALL_PATH/mp3agic-apps.jar:$MP3AGIC_INSTALL_PATH/mp3agic.jar" com.mpatric.mp3agic.app.Mp3Catalog ${OPTIONS[@]} "${1}"
    fi
    shift
  fi
done
