#!/bin/sh
if test "$1" = ""; then
  VERSION=`java -cp $MP3AGIC_INSTALL_PATH/mp3agic-apps.jar com.mpatric.mp3agic.app.LibVersion`
  echo
  echo mp3details $VERSION
  echo
  echo "Displays the details of the specified mp3 file(s)"
  echo
  echo "Usage: mp3details [filename specifier]"
  echo "Example: mp3details myaudio/*.mp3"
  echo
  exit 2
fi
fin=0
while ! ((fin)); do
  if test "$1" = ""; then
    fin=1
  else
    if [ -f "${1}" ]; then
      java -cp $MP3AGIC_INSTALL_PATH/mp3agic-apps.jar com.mpatric.mp3agic.app.Mp3Details "${1}"
    fi
    shift
  fi
done
